### ISSUE TITLE
Integrate whiteboard to existing app

### ISSUE THREAD

**Issue by ugintl** [mgsweet/SharedWhiteBoard#1]
I want to integrate whiteboard to my existing app. It already have chatting. I just want to integrate collaborative tool.

**Comment by mgsweet** [comment]
I don't think it would be an easy job since the main part of this app is the whiteboard. And even I added the chat part at the end of the project. You can go back to commit [997acdd](https://github.com/mgsweet/SharedWhiteBoard/commit/997acdd399fb903b04c000a83cce9f251e68ae12) to check the simple code of the off-line version of whiteboard to find some ideas. I should wrote the code in a more modular way but it was really a rush to finish the code at the end of the semester. Feel sorry about that.
